### ISSUE TITLE
conditional check failed during byte stream write

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega-client-rust#198] opened 2020-12-03 20:19 UTC
**Problem description**
Running a Pravega write benchmark returned the error `conditional check failed` after 5 minutes.
```
[2020-12-03T19:55:48Z DEBUG pravega_client_rust::reactor::segment_writer] setting up append for writer:WriterId(199441243869397512482901218303664300474)/segment:ScopedSegmen
t { scope: Scope { name: "examples" }, stream: Stream { name: "pbr-15-100000MB-1seg-pod0" }, segment: Segment { number: 0, tx_id: None } } 
[2020-12-03T19:55:48Z DEBUG pravega_client_rust::reactor::segment_writer] append setup completed for writer:WriterId(199441243869397512482901218303664300474)/segment:ScopedS
egment { scope: Scope { name: "examples" }, stream: Stream { name: "pbr-15-100000MB-1seg-pod0" }, segment: Segment { number: 0, tx_id: None } } 
[2020-12-03T19:55:48Z INFO  pravega_client_rust::reactor::segment_writer] finished setting up connection 
[2020-12-03T19:55:48Z DEBUG pravega_client_rust::reactor::segment_writer] flushing 1 events of total size 5242880 to segment "examples/pbr-15-100000MB-1seg-pod0/0.#epoch.0" 
based on offset Some(20683161600); event segment writer id WriterId(199441243869397512482901218303664300474)/connection id: 42a66895-5739-498f-9da7-020504476b62 
[2020-12-03T19:55:48Z WARN  pravega_client_rust::reactor::reactors] conditional check failed ConditionalCheckFailedCommand { writer_id: 199441243869397512482901218303664300474, event_number: 3946, request_id: 3949 }
```

The benchmark application used is https://eos2git.cec.lab.emc.com/faheyc/historical-stream-processing/tree/master/pravega-benchmark-rust. This uses pravega-client-rust commit 2c03fd8. The server uses https://github.com/claudiofahey/pravega/commit/101f0894b77e2d0bcf95eacf77f44647d61bbc9a.

**Problem location**
Unknown.

**Suggestions for an improvement**
Unknown.

**Comment by claudiofahey** [comment] 2020-12-03 20:20
Full client logs are here:
[pravega-benchmark-rust-write-job.log](https://github.com/pravega/pravega-client-rust/files/5638723/pravega-benchmark-rust-write-job.log)

**Comment by claudiofahey** [comment] 2020-12-08 21:50
This may have a similar cause as https://github.com/pravega/pravega-client-rust/issues/174.

**Comment by claudiofahey** [comment] 2020-12-08 22:42
I have run the write benchmark again with the latest commit b69506f593e5c025ed29a82d435b9cea49875911 and it appears to work well. I successfully wrote a total of 200 GB in about 30 minutes.

**Comment by Tristan1900** [comment] 2020-12-12 00:05
Thanks for the report, this is an interesting problem. 

What happened is that a connection error happened during the running and client resended the inflight events. However, the event actually has been written on the server already so the `ConditionalCheckFailed` has returned. 

I'm not sure what's the correct way to handle this. The reason is that we don't know if `ConditionalCheckFailed` is true or false. It is true if some other writer indeed write something, it is false if it is casued by connection failure such as this issue. To be more complicated, connection failure and other writer's interruption could happen at the same time. I guess the only way to know is to read the data from server and check if it is what application has to write.

What do you think? @tkaitchuck Thanks

**Comment by claudiofahey** [comment] 2020-12-12 00:21
I think we want to maintain the guarantee that the byte stream writer knows exactly what offset it will write to. This is the main reason for using conditional writes. A nice-to-have but not necessarily guaranteed feature is that it will panic if it detects that another writer wrote to the same stream. If a writer performs a retry and then encounters ConditionalCheckFailed, I think it would be safe to assume that its prior write succeeded and ignore this error. If it encounters ConditionalCheckFailed when a retry was not sent, then we can assume another writer wrote and panic.

**Comment by Tristan1900** [comment] 2020-12-12 00:38
thanks @claudiofahey, that's what I thought at first. But it could be that if a connection failure happens at the same time another writer writes the segment. Client performs retry due to connection failure and receives `ConditionalCheckFailed` and assumes it is ok. But actually another writer has written something already.

**Comment by claudiofahey** [comment] 2020-12-12 01:46
Ok I understand your point now. For at least the GStreamer use case, as soon as a 2nd writer makes a successful write, there will be some corruption of the video stream which might result in a few lost video frames. Eventually, one or both writers will get a ConditionalCheckFailed when it did not retry and it will panic. This will result in some limited corruption and even some interleaving but I would expect it to be detected within a few seconds. I think this would be acceptable.
For a use case in which there cannot be interleaving of data, I think we would need to have some sort of locking mechanism but we probably do not want to tackle this now.

**Comment by tkaitchuck** [comment] 2020-12-18 01:40
The full segment of the log is:
```
[2020-12-03T19:55:45Z DEBUG pravega_client_rust::reactor::segment_writer] flushing 1 events of total size 5242880 to segment "examples/pbr-15-100000MB-1seg-pod0/0.#epoch.0" based on offset Some(20677918720); event segment writer id WriterId(199441243869397512482901218303664300474)/connection id: 4b7ce931-ce89-4454-a745-730a67f221fd 
[2020-12-03T19:55:47Z DEBUG pravega_client_rust::reactor::reactors] data appended for writer WriterId(199441243869397512482901218303664300474), latest event id is: 3945 
[2020-12-03T19:55:47Z DEBUG pravega_client_rust::byte_stream] writing payload of size 5242880 based on offset 20693647360 
[2020-12-03T19:55:47Z DEBUG pravega_client_rust::reactor::segment_writer] flushing 1 events of total size 5242880 to segment "examples/pbr-15-100000MB-1seg-pod0/0.#epoch.0" based on offset Some(20683161600); event segment writer id WriterId(199441243869397512482901218303664300474)/connection id: 4b7ce931-ce89-4454-a745-730a67f221fd 
[2020-12-03T19:55:48Z WARN  pravega_client_rust::reactor::segment_writer] connection failed to read data back from segmentstore due to Read { part: "header", source: ReadData { endpoint: PravegaNodeUri("10.233.96.28:12345"), source: Custom { kind: UnexpectedEof, error: "early eof" }, backtrace: Backtrace(()) }, backtrace: Backtrace(()) }, closing listener task 4b7ce931-ce89-4454-a745-730a67f221fd 
[2020-12-03T19:55:48Z INFO  pravega_client_rust::reactor::segment_writer] listener task shut down 4b7ce931-ce89-4454-a745-730a67f221fd 
[2020-12-03T19:55:48Z WARN  pravega_client_rust::reactor::reactors] reconnect for writer WriterInfo { segment: ScopedSegment { scope: Scope { name: "examples" }, stream: Stream { name: "pbr-15-100000MB-1seg-pod0" }, segment: Segment { number: 0, tx_id: None } }, connection_id: 4b7ce931-ce89-4454-a745-730a67f221fd, writer_id: WriterId(199441243869397512482901218303664300474) } 
[2020-12-03T19:55:48Z DEBUG pravega_client_rust::reactor::segment_writer] Reconnecting segment writer WriterId(199441243869397512482901218303664300474) 
[2020-12-03T19:55:48Z INFO  pravega_client_rust::reactor::segment_writer] setup connection; segment_writer_id=960afc82d5e202836548b98b1645a1ba segment=examples/pbr-15-100000MB-1seg-pod0/0.#epoch.0
[2020-12-03T19:55:48Z INFO  pravega_client_rust::reactor::segment_writer] setting up connection for segment writer 
[2020-12-03T19:55:48Z DEBUG tower_balance::p2c::service] updating from discover 
[2020-12-03T19:55:48Z DEBUG hyper::client::connect::http] connected to 10.233.59.0:9090 
[2020-12-03T19:55:48Z DEBUG h2::client] binding client connection 
[2020-12-03T19:55:48Z DEBUG h2::client] client connection bound 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_write] send; frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 } 
[2020-12-03T19:55:48Z DEBUG tower_buffer::worker] service.ready=true processing request 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_read] received; frame=Settings { flags: (0x0), max_concurrent_streams: 2147483647, initial_window_size: 1048576, max_header_list_size: 8192 } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_write] send; frame=Settings { flags: (0x1: ACK) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_read] received; frame=WindowUpdate { stream_id: StreamId(0), size_increment: 983041 } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_read] received; frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_write] send; frame=Headers { stream_id: StreamId(5), flags: (0x4: END_HEADERS) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_write] send; frame=Data { stream_id: StreamId(5) } 
[2020-12-03T19:55:48Z DEBUG hyper::proto::h2::client] connection error: Transport endpoint is not connected (os error 107) 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_write] send; frame=Data { stream_id: StreamId(5), flags: (0x1: END_STREAM) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_read] received; frame=Headers { stream_id: StreamId(5), flags: (0x4: END_HEADERS) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_read] received; frame=Data { stream_id: StreamId(5) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_read] received; frame=Headers { stream_id: StreamId(5), flags: (0x5: END_HEADERS | END_STREAM) } 
[2020-12-03T19:55:48Z INFO  pravega_rust_client_auth] token expiry time 1607025348 is in the refresh threshold 1607025353, need to refresh token 
[2020-12-03T19:55:48Z DEBUG pravega_rust_client_auth] token does not exist or is about to expire, refresh to get a new one 
[2020-12-03T19:55:48Z DEBUG tower_balance::p2c::service] updating from discover 
[2020-12-03T19:55:48Z DEBUG tower_buffer::worker] service.ready=true processing request 
[2020-12-03T19:55:48Z DEBUG hyper::client::connect::dns] resolving host="nautilus-pravega-controller.nautilus-pravega.svc.cluster.local" 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_write] send; frame=Headers { stream_id: StreamId(7), flags: (0x4: END_HEADERS) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_write] send; frame=Data { stream_id: StreamId(7) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_write] send; frame=Data { stream_id: StreamId(7), flags: (0x1: END_STREAM) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_read] received; frame=Headers { stream_id: StreamId(7), flags: (0x4: END_HEADERS) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_read] received; frame=Data { stream_id: StreamId(7) } 
[2020-12-03T19:55:48Z DEBUG h2::codec::framed_read] received; frame=Headers { stream_id: StreamId(7), flags: (0x5: END_HEADERS | END_STREAM) } 
[2020-12-03T19:55:48Z DEBUG pravega_client_rust::reactor::segment_writer] setting up append for writer:WriterId(199441243869397512482901218303664300474)/segment:ScopedSegment { scope: Scope { name: "examples" }, stream: Stream { name: "pbr-15-100000MB-1seg-pod0" }, segment: Segment { number: 0, tx_id: None } } 
[2020-12-03T19:55:48Z DEBUG pravega_client_rust::reactor::segment_writer] append setup completed for writer:WriterId(199441243869397512482901218303664300474)/segment:ScopedSegment { scope: Scope { name: "examples" }, stream: Stream { name: "pbr-15-100000MB-1seg-pod0" }, segment: Segment { number: 0, tx_id: None } } 
[2020-12-03T19:55:48Z INFO  pravega_client_rust::reactor::segment_writer] finished setting up connection 
[2020-12-03T19:55:48Z DEBUG pravega_client_rust::reactor::segment_writer] flushing 1 events of total size 5242880 to segment "examples/pbr-15-100000MB-1seg-pod0/0.#epoch.0" based on offset Some(20683161600); event segment writer id WriterId(199441243869397512482901218303664300474)/connection id: 42a66895-5739-498f-9da7-020504476b62 
[2020-12-03T19:55:48Z WARN  pravega_client_rust::reactor::reactors] conditional check failed ConditionalCheckFailedCommand { writer_id: 199441243869397512482901218303664300474, event_number: 3946, request_id: 3949 } 
[2020-12-03T19:55:48Z DEBUG pravega_client_rust::byte_stream] writing payload of size 5242880 based on offset 20698890240 
```
What's happening here is that event 3946 was written right before the connection drop. However it was not acked. So when the reconnect happened the AppendSetup reply should have acked it. We don't have a log of the actual reply value (we should add that).
There are two options, it was still inflight on the server and was not included, in which case the "issue" was server side and would have been harmless if the client simply re-tried the setup append. 
Alternatively the client could have handled the AppendSetup incorrectly.

**Comment by Tristan1900** [comment] 2020-12-18 01:58
Thanks Tom. 

Today I tried to reproduce this issue by closing the connection every 10 events so it can trigger a reconnection. However, it seems that client has correctly handled the reconnection and everything works fine, the returned event number from AppendSetup is correct and we have logic to ack up to that event number so no ConditionalCheckFailure happens. (will add the returned event number to log)

I guess what happened is like you said. the event was not included by the time client called SetupAppend.

**Comment by Tristan1900** [comment] 2021-02-11 01:48
reopen this issue based on latest finding [here](https://github.com/pravega/pravega/pull/5713).

**Closed** 2021-09-17 19:31 UTC
Labels: bug, Priority
